/* 이 파일은 scripts/assets/textures.mjs가 만든다. 직접 고치지 말 것. */

import type { Material } from "@/scene/types";

/**
 * Poly Haven CC0 PBR 마감재.
 * surface는 이 마감을 바를 수 있는 면 — 재질 고르기 화면이 이 값으로 묶어 보여 준다.
 */
export interface TexturedMaterial extends Material {
  surface: ("floor" | "wall" | "ceiling" | "furniture")[];
  /** 거칠기·금속감·AO가 한 장에 들어 있는 맵 (R=AO, G=roughness, B=metallic) */
  armMapUrl: string | null;
}

export const TEXTURED_MATERIALS: TexturedMaterial[] = [
  {
    id: "mat_ph_laminate_floor_02",
    name: "라미네이트 마루",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2,
    textureUrl: "/textures/laminate_floor_02/diff.jpg",
    normalMapUrl: "/textures/laminate_floor_02/nor.jpg",
    armMapUrl: "/textures/laminate_floor_02/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","마루","강마루","laminate","wood"],
  },
  {
    id: "mat_ph_plank_flooring",
    name: "원목 마루",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.2,
    textureUrl: "/textures/plank_flooring/diff.jpg",
    normalMapUrl: "/textures/plank_flooring/nor.jpg",
    armMapUrl: "/textures/plank_flooring/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","마루","원목","plank","wood"],
  },
  {
    id: "mat_ph_plank_flooring_02",
    name: "화이트 오크 마루",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.2,
    textureUrl: "/textures/plank_flooring_02/diff.jpg",
    normalMapUrl: "/textures/plank_flooring_02/nor.jpg",
    armMapUrl: "/textures/plank_flooring_02/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","마루","오크","화이트","wood"],
  },
  {
    id: "mat_ph_dark_wooden_planks",
    name: "다크 월넛 마루",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.2,
    textureUrl: "/textures/dark_wooden_planks/diff.jpg",
    normalMapUrl: "/textures/dark_wooden_planks/nor.jpg",
    armMapUrl: "/textures/dark_wooden_planks/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","마루","월넛","다크","wood"],
  },
  {
    id: "mat_ph_rectangular_parquet",
    name: "헤링본 파케트",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.6,
    textureUrl: "/textures/rectangular_parquet/diff.jpg",
    normalMapUrl: "/textures/rectangular_parquet/nor.jpg",
    armMapUrl: "/textures/rectangular_parquet/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","파케트","헤링본","parquet","wood"],
  },
  {
    id: "mat_ph_diagonal_parquet",
    name: "대각 파케트",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.6,
    textureUrl: "/textures/diagonal_parquet/diff.jpg",
    normalMapUrl: "/textures/diagonal_parquet/nor.jpg",
    armMapUrl: "/textures/diagonal_parquet/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","파케트","대각","parquet"],
  },
  {
    id: "mat_ph_marble_01",
    name: "화이트 마블",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.4,
    textureUrl: "/textures/marble_01/diff.jpg",
    normalMapUrl: "/textures/marble_01/nor.jpg",
    armMapUrl: "/textures/marble_01/arm.jpg",
    heightMapUrl: null,
    surface: ["floor","wall"],
    tags: ["floor","wall","바닥","벽","대리석","마블","marble","luxury"],
  },
  {
    id: "mat_ph_floor_tiles_06",
    name: "포세린 타일",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.2,
    textureUrl: "/textures/floor_tiles_06/diff.jpg",
    normalMapUrl: "/textures/floor_tiles_06/nor.jpg",
    armMapUrl: "/textures/floor_tiles_06/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","타일","포세린","tile"],
  },
  {
    id: "mat_ph_floor_tiles_02",
    name: "무광 그레이 타일",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.2,
    textureUrl: "/textures/floor_tiles_02/diff.jpg",
    normalMapUrl: "/textures/floor_tiles_02/nor.jpg",
    armMapUrl: "/textures/floor_tiles_02/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","타일","그레이","tile"],
  },
  {
    id: "mat_ph_terracotta_floor_tiles",
    name: "테라코타 타일",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.4,
    textureUrl: "/textures/terracotta_floor_tiles/diff.jpg",
    normalMapUrl: "/textures/terracotta_floor_tiles/nor.jpg",
    armMapUrl: "/textures/terracotta_floor_tiles/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","타일","테라코타","terracotta"],
  },
  {
    id: "mat_ph_smooth_concrete_floor",
    name: "폴리싱 콘크리트",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 3,
    textureUrl: "/textures/smooth_concrete_floor/diff.jpg",
    normalMapUrl: "/textures/smooth_concrete_floor/nor.jpg",
    armMapUrl: "/textures/smooth_concrete_floor/arm.jpg",
    heightMapUrl: null,
    surface: ["floor"],
    tags: ["floor","바닥","콘크리트","폴리싱","concrete","industrial"],
  },
  {
    id: "mat_ph_white_plaster_02",
    name: "화이트 미장",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 4,
    textureUrl: "/textures/white_plaster_02/diff.jpg",
    normalMapUrl: "/textures/white_plaster_02/nor.jpg",
    armMapUrl: "/textures/white_plaster_02/arm.jpg",
    heightMapUrl: null,
    surface: ["wall","ceiling"],
    tags: ["wall","ceiling","벽","천장","도장","미장","화이트","plaster"],
  },
  {
    id: "mat_ph_beige_wall_001",
    name: "베이지 도장",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 4,
    textureUrl: "/textures/beige_wall_001/diff.jpg",
    normalMapUrl: "/textures/beige_wall_001/nor.jpg",
    armMapUrl: "/textures/beige_wall_001/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","도장","베이지","warm"],
  },
  {
    id: "mat_ph_beige_wall_002",
    name: "웜 아이보리 도장",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 4,
    textureUrl: "/textures/beige_wall_002/diff.jpg",
    normalMapUrl: "/textures/beige_wall_002/nor.jpg",
    armMapUrl: "/textures/beige_wall_002/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","도장","아이보리","warm"],
  },
  {
    id: "mat_ph_grey_plaster",
    name: "그레이 미장",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 4,
    textureUrl: "/textures/grey_plaster/diff.jpg",
    normalMapUrl: "/textures/grey_plaster/nor.jpg",
    armMapUrl: "/textures/grey_plaster/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","도장","그레이","미장"],
  },
  {
    id: "mat_ph_plastered_wall_04",
    name: "거친 미장",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 3.2,
    textureUrl: "/textures/plastered_wall_04/diff.jpg",
    normalMapUrl: "/textures/plastered_wall_04/nor.jpg",
    armMapUrl: "/textures/plastered_wall_04/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","미장","텍스처","plaster"],
  },
  {
    id: "mat_ph_white_stucco",
    name: "스투코",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 3.2,
    textureUrl: "/textures/white_stucco/diff.jpg",
    normalMapUrl: "/textures/white_stucco/nor.jpg",
    armMapUrl: "/textures/white_stucco/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","스투코","stucco","natural"],
  },
  {
    id: "mat_ph_ceiling_interior",
    name: "천장 텍스",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.4,
    textureUrl: "/textures/ceiling_interior/diff.jpg",
    normalMapUrl: "/textures/ceiling_interior/nor.jpg",
    armMapUrl: "/textures/ceiling_interior/arm.jpg",
    heightMapUrl: null,
    surface: ["ceiling"],
    tags: ["ceiling","천장","텍스","ceiling","office"],
  },
  {
    id: "mat_ph_painted_brick",
    name: "화이트 벽돌",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.6,
    textureUrl: "/textures/painted_brick/diff.jpg",
    normalMapUrl: "/textures/painted_brick/nor.jpg",
    armMapUrl: "/textures/painted_brick/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","벽돌","화이트","brick"],
  },
  {
    id: "mat_ph_brick_wall_13",
    name: "적벽돌",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.6,
    textureUrl: "/textures/brick_wall_13/diff.jpg",
    normalMapUrl: "/textures/brick_wall_13/nor.jpg",
    armMapUrl: "/textures/brick_wall_13/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","벽돌","적벽돌","brick","industrial"],
  },
  {
    id: "mat_ph_brown_planks_03",
    name: "우드 월패널",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.4,
    textureUrl: "/textures/brown_planks_03/diff.jpg",
    normalMapUrl: "/textures/brown_planks_03/nor.jpg",
    armMapUrl: "/textures/brown_planks_03/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","월패널","우드","wood"],
  },
  {
    id: "mat_ph_dark_wood",
    name: "다크 우드 패널",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 2.4,
    textureUrl: "/textures/dark_wood/diff.jpg",
    normalMapUrl: "/textures/dark_wood/nor.jpg",
    armMapUrl: "/textures/dark_wood/arm.jpg",
    heightMapUrl: null,
    surface: ["wall"],
    tags: ["wall","벽","월패널","다크","wood"],
  },
  {
    id: "mat_ph_hessian_230",
    name: "린넨 패브릭",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1,
    textureUrl: "/textures/hessian_230/diff.jpg",
    normalMapUrl: "/textures/hessian_230/nor.jpg",
    armMapUrl: "/textures/hessian_230/arm.jpg",
    heightMapUrl: null,
    surface: ["furniture"],
    tags: ["furniture","패브릭","린넨","소파","fabric"],
  },
  {
    id: "mat_ph_cotton_jersey",
    name: "코튼 패브릭",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1,
    textureUrl: "/textures/cotton_jersey/diff.jpg",
    normalMapUrl: "/textures/cotton_jersey/nor.jpg",
    armMapUrl: "/textures/cotton_jersey/arm.jpg",
    heightMapUrl: null,
    surface: ["furniture"],
    tags: ["furniture","패브릭","코튼","소파","fabric"],
  },
  {
    id: "mat_ph_brown_leather",
    name: "브라운 가죽",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1,
    textureUrl: "/textures/brown_leather/diff.jpg",
    normalMapUrl: "/textures/brown_leather/nor.jpg",
    armMapUrl: "/textures/brown_leather/arm.jpg",
    heightMapUrl: null,
    surface: ["furniture"],
    tags: ["furniture","가죽","leather","소파","브라운"],
  },
  {
    id: "mat_ph_dirty_carpet",
    name: "카펫",
    baseColor: "#ffffff",
    roughness: 1,
    metallic: 0,
    scale: 1.6,
    textureUrl: "/textures/dirty_carpet/diff.jpg",
    normalMapUrl: "/textures/dirty_carpet/nor.jpg",
    armMapUrl: "/textures/dirty_carpet/arm.jpg",
    heightMapUrl: null,
    surface: ["floor","furniture"],
    tags: ["floor","furniture","카펫","러그","carpet","fabric"],
  },
];
